module.exports =[
    {
        username:"student1",
        email:"student1@gmail.com",
        password:"Student@123"
    },
    {
        username:"student2",
        email:"student2@gmail.com",
        password:"Student@123"
    },
    {
        username:"student3",
        email:"student3@gmail.com",
        password:"Student@123"
    },
    {
        username:"student4",
        email:"student4@gmail.com",
        password:"Student@123"
    },
    {
        username:"student5",
        email:"student5@gmail.com",
        password:"Student@123"
    },
    {
        username:"student6",
        email:"student6@gmail.com",
        password:"Student@123"
    },
]